
spring.application.name=student-Registration

# Profile
#spring.profiles.active=dev
spring.profiles.active=prod

#context path
server.servlet.context-path=/

# Server
server.port=8081
#server.servlet.context-path=/FLDMGT/


# Logging
logging.file.name=logs/SPRMS_REGIS.log
logging.logback.rollingpolicy.max-file-size=20MB
logging.logback.rollingpolicy.max-history=30

# Maximum file size
spring.servlet.multipart.max-file-size=50MB

# Maximum request size (sum of all files)
spring.servlet.multipart.max-request-size=50MB

#upload directory
#This file uploads path is set to PC drive
#file.upload-dir=D:/RCSC_SPRMS/SPRMS/uploads

#this file path is use for testing
file.upload-dir=${UPLOAD_DIR}

#email server setting
spring.mail.host=smtp.gmail.com
spring.mail.port=587

spring.mail.username=${MAIL_USERNAME}
spring.mail.password=${MAIL_PASSWORD}

#spring.mail.properties.mail.smtp.auth=true
#spring.mail.properties.mail.smtp.starttls.enable=true
